// src/components/Header/Header.jsx
import Swap from './Swap';
import LightDarkToggle from './LightDarkToggle';

const Header = ({}) => {
  return (
    <header className='flex items-center justify-between text-center w-full mt-2.5 mb-5 sm:mb-10'>
      <p className='text-2xl font-bold text-center drop-shadow-lg sm:text-4xl bg-gradient-to-r from-indigo-500 via-fuchsia-500 to-rose-500 text-transparent bg-clip-text'>
        Nick Latcham
      </p>
      <div className='flex'>
        <LightDarkToggle />
        <Swap />
      </div>
    </header>
  );
};

export default Header;

// new/src/components/Header.svelte
<script lang="ts">
	import { onMount } from 'svelte';
</script>

<header>
	<a href="/">Nick Latcham</a>
	<nav>
		<ul>
			<li>
				<a href="/about">About</a>
			</li>
			<li><a href="/projects">Projects</a></li>
		</ul>
	</nav>
</header>

<style>
	header {
		width: 100%;
		margin-top: 0;
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	ul {
		display: flex;
	}

	li {
		padding-inline: 1ch;
		font-size: clamp(1em, 1vw, 2vw);
	}

	header > a {
		font-size: clamp(2rem, 2vw, 4vw);
		font-weight: 700;

		&:hover {
			color: transparent;
			background: linear-gradient(to right, red, orange, purple);
			background-clip: text;		}
	}
</style>
