// src/components/Footer.jsx
const Footer = () => {
  return (
    <footer className="flex justify-center mt-10">
      <p className="text-sm text-gray-400 sm:ml-4 sm:pl-4  sm:py-2 sm:mt-0 mt-4">
        © 2023 Nick Latcham — <a href="https://github.com/nicklatch">Github</a>
      </p>
    </footer>
  );
};
export default Footer;

// src/components/Footer.svelte
<script lang="ts">
  import SvelteSvg from './SvelteSVG.svelte';
</script>

<footer>
  <p>8/21&nbsp;</p>
  <p>© 2023 Nick Latcham | Made With &nbsp;</p>
  <SvelteSvg />
</footer>

<style>
  footer {
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  p {
    text-align: center;
    font-size: clamp(8px, 0.8rem, 1.5rem);
  }
</style>
