// new/src/components/Header.svelte
<script lang="ts">
	import { onMount } from 'svelte';
</script>

<header>
	<a href="/">Nick Latcham</a>
	<nav>
		<ul>
			<li>
				<a href="/about">About</a>
			</li>
			<li><a href="/projects">Projects</a></li>
		</ul>
	</nav>
</header>

<style>
	header {
		width: 100%;
		margin-top: 0;
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	ul {
		display: flex;
	}

	li {
		padding-inline: 1em;
	}

	header > a {
		font-size: clamp(1.5em, 3vw, 2.5em);
	}
</style>

// src/components/Header.jsx
const Header = () => {
  return (
    <header className='flex justify-between w-full mb-10 ring-4 shadow-lg shadow-blue-500/50 p-4 rounded-3xl'>
      <p className='text-5xl font-bold text-white text-center drop-shadow-lg'>
        Nick Latcham
      </p>
      <div>
        <button className='btn btn-outline'>About</button>
        <button className='btn btn-outline mx-2'>Projects</button>
        <button className='btn btn-outline'>Blog</button>
      </div>
    </header>
  );
};

export default Header;
